plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}
android {
    namespace "com.gal1n.dexkeyboard"
    compileSdk 35
    defaultConfig {
        applicationId "com.gal1n.dexkeyboard"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
    testOptions { unitTests.returnDefaultValues = true }
}
dependencies {
    testImplementation "junit:junit:4.13.2"
}
